### ISSUE TITLE
Define MQTT Topics

### ISSUE THREAD

**Issue by Flipez** [Herzmut-Games/hkick-core#4]
### Score
- [x] score/red `3`
- [x] score/white `4`
- [x] score/decrease `"white" or "red"`
- [x] score/increase `"white" or "red"`
- [x] score/reset `"reset"`

### Game
- [x] game/start `"start"`
- [x] game/end  `"start"`

### Sound
- [x] sound/play `"prepare.mp3"`
- [ ] sound/stop `"stop"`
- [x] sound/volume `0-100`
- [ ] sound/mode `"quake"`

### Spotify
- [x] spotify/status `"play" or "change" or "stop"`
- [x] spotify/title `"YMCA"`

**Comment by c-stoeckl** [comment]
Mostly done, will reopen if needed.
